# Configure main menu and social menu.
#main:
#  - identifier: home
#    name: Home
#    url: /
#    params:
#      icon: home
#      newtab: true

social:
  - identifier: github
    name: GitHub
    url: https://github.com/ctx42
    params:
      icon: brand-github
  - identifier: twitter
    name: Twitter
    url: https://x.com/context42
    params:
      icon: brand-twitter
  - identifier: rss
    name: RSS
    url: index.xml
    params:
      icon: rss
