# Pages placed under these sections will be shown on homepage and archive page.
mainSections:
  - post

# Output page's full content in RSS.
rssFullContent: true

favicon: /favicon-ctx.png
footer:
  since: 2020
  customText: ""
dateFormat:
  published: Jan 02, 2006
  lastUpdated: Jan 02, 2006 15:04 MST
sidebar:
  emoji: ""
  subtitle: Improving the daily work is more important than doing the daily work.
  avatar:
    enabled: true
    local: true
    src: img/ctx42.png
article:
  headingAnchor: false
  math: false
  readingTime: true
  license:
    enabled: true
    default: Licensed under CC BY-NC-SA 4.0
widgets:
  homepage:
    - type: search
    - type: archives
      params:
        limit: 5
    - type: categories
      params:
        limit: 10
    - type: tag-cloud
      params:
        limit: 10
  page:
    - type: toc
opengraph:
  twitter:
    site: ""
    card: summary_large_image
defaultImage:
  opengraph:
    enabled: false
    local: false
    src: ""
colorScheme:
  toggle: false
  default: dark
imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true
comments:
  enabled: false
  provider: disqus
  disqusjs:
    shortname: ""
    apiUrl: ""
    apiKey: ""
    admin: ""
    adminLabel: ""
  utterances:
    repo: ""
    issueTerm: pathname
    label: ""
  remark42:
    host: ""
    site: ""
    locale: ""
  vssue:
    platform: ""
    owner: ""
    repo: ""
    clientId: ""
    clientSecret: ""
    autoCreateIssue: false
  waline:
    serverURL: ""
    lang: ""
    visitor: ""
    avatar: ""
    emoji:
      - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
    requiredMeta:
      - name
      - email
      - url
    placeholder: ""
    locale:
      admin: Admin
  twikoo:
    envId: ""
    region: ""
    path: ""
    lang: ""
  cactus:
    defaultHomeserverUrl: https://matrix.cactus.chat:8448
    serverName: cactus.chat
    siteName: ""
  giscus:
    repo: ""
    repoID: ""
    category: ""
    categoryID: ""
    mapping: ""
    lightTheme: ""
    darkTheme: ""
    reactionsEnabled: 1
    emitMetadata: 0
  gitalk:
    owner: ""
    admin: ""
    repo: ""
    clientID: ""
    clientSecret: ""
  cusdis:
    host: ""
    id: ""
